### ISSUE TITLE
Consensus

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#13]
Tracking ticket for consensus.

- [ ] GHOST & DECOR+ consensus #244.
- [x] Add block to the top of the chain #231.
- [ ] Handle orphaned blocks #59. This implements consensus, basically.
- [ ] Warn when merging a chain that's more than N blocks ahead #287.
- [ ] Handle orphaned blocks #59.
- [ ] Block with no parent #64.
- [ ] Return transactions to the mempool when discarding a block #233.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784776
