### ISSUE TITLE
[Feature] Windows Support

### ISSUE THREAD

**Issue by tolbrino** [aeternity/epoch#1771]
Experimental support via WSL has been documented in #1710.

The next step is running epoch directly on Windows including CUDA support for GPU mining.

# Subtasks

- [x] epoch Erlang code can be compiled
- [x] epoch C code can be compiled
  - [x] ~~erlexec~~ replaced with OTP-only code 
  - [x] enacl
  - [x] ~~rocksdb and its C dependencies (e.g. snappy)~~ replaced by Mnesia native in #1849
- [x] chain sync working (ram-only)
- [x] chain sync working (persisting using disc)
- [x] CPU mining working outside of epoch
- [x] CPU mining working inside of epoch
- [x] GPU mining working outside of epoch
- [x] GPU mining working inside of epoch
- [ ] key_gen working, requires relx and rebar changes
- [ ] configuration working
  - [ ] data directory
  - [ ] log directory
  - [ ] sane defaults for mining
  - [ ] config file in $HOME
- [ ] packaging and installation working
- [ ] documentation
  - [ ] build
  - [ ] packaging
  - [ ] installation

**Comment by tolbrino** [comment]
These tasks are tracked in https://www.pivotaltracker.com/epic/show/4168968 going forward. Closing this ticket.
