### ISSUE TITLE
Мempool

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#221]
Tracking ticket for all the things mempool.

- [x] Implement the mempool #16.
- [ ] Update mempool when receiving transactions #72.
- [ ] Add new transactions to block while mining #68.
- [ ] Delete transactions from the mempool when adding a block to our chain #232.
- [ ] Return transactions to the mempool when discarding a block #233.
- [x] Syncing and the mempool #186.
- [ ] Transactions are not to be added to the mempool if they already exist #230.

**Comment by sennui** [comment]
moving the note here: 

Add ticket to improve mempool (batch API for delete) Consult with Luca. I commented and accepted the first PR #240)

**Comment by sennui** [comment]
where do we want to catch duplicated transaction. Current solution will not catch two same txs with different fees

**Comment by sennui** [comment]
cc: @lucafavatella ^^

**Comment by lucafavatella** [comment]
@zp-sd  I added in backlog of [“Core” project](https://github.com/aeternity/epoch/projects/1) a note “Optimize mempool”.

Currently in master the mempool process is only responsible for (1) initializing the txs in-memory storage and (2) proxying peek/put/delete operations. Wrt potential future changes to mempool for limiting transfer of data between heaps of mempool process and its client (that we briefly mentioned yesterday), responsibility (2) may be removed from mempool process by choosing an in-memory sorted ETS table (and catch a few error cases when attempting to peek multiple txs) - hence removing the mempool process from peek/put/delete operations. Though I suggest deferring optimizations like this to after the usage of the mempool is more firmly established e.g. nature of key, potential secondary indexes, and guarantee of additional constraints needing the serializing process.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784794
