### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#223]
Tracking ticket for everything related to syncing nodes.

- [ ] Bootstrap peer discovery #288.
- [ ] Process received block #281.
- [ ] Broadcast block after adding it to the top of our chain #295.
- [ ] Fill in missing blocks #292.
- [ ] Process received transaction #279.

**Comment by sennui** [comment]
auto config pending from Ulf

**Comment by sennui** [comment]
checking the last checkbox! Syncing as scoped here is complete. Remaining parts are tracked in another services, example: mempool.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784774
