### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#23]
This is the tracking ticket for our transactions.

- [x] Coinbase transaction #43.
- [ ] Spend transaction #185.
- [ ] Calculate transaction fee #246.
- [ ] Process received transaction #279.
- [ ] Broadcast transaction #62.
- [ ] Add new transactions to block while mining #68.
- [ ] Avoid transaction malleability issues #180.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784793
