### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#235]
Tracking ticket for all things mining.

- [ ] Stop the current mining attempt when the top of the chain is modified #234.
- [x] Do not remove transactions from the mempool while mining #236.
- [x] Inform user about the progress of mining at regular intervals #229.
- [ ] Add new transactions to block while mining #68.
- [ ] Build block proposal #280.
- [ ] Fix wrong interface with Cuckoo Cycle #274.
- [ ] Consider including multiple versions of the Cuckoo Cycle NIF in the release #282.
- [ ] Build block proposal #280.
- [ ] State updates between the miner and the state process #303.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784782
