### ISSUE TITLE
State of the world

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#237]
Parent ticket to track the state of the world.

- [x] Rebuild state of the world when a stronger chain is found #226.
- [ ] Authenticated Dynamic Dictionaries #86.
- [ ] Checkpoint state trees #276.
- [ ] State updates between the miner and the state process #303.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784777
