### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#241]
Tracking ticket for all things that need to be persisted.

- [ ] Persist authenticated dynamic dictionaries #275.
- [ ] Store blocks in RocksDB and fetch them #9.
- [ ] Persist the blockchain between node restarts #113.
- [ ] Persist state of the world between node restarts #61.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784797
