### ISSUE TITLE
HTTP & WebSockets

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#242]
Tracking ticket for HTTP and WebSocket APIs.

- [ ] Land websockets for the secure internal interface #117.
- [ ] Implement websocket endpoints #296.
- [ ] Fix Swagger code generation #178.
- [ ] Swagger codegen for websockets #278.
- [ ] Secure the HTTP API #28.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784790
