### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#277]
Tracking tickets for all the things that we are validating.

- [ ] Check that each block has no more than one coinbase transaction #60.
- [ ] Process received transaction #279.
- [ ] Fill in missing blocks #292.
- [ ] Avoid transaction malleability issues #180.
- [ ] Validate received block #17.
- [ ] Make sure the block reward cannot be claimed for the next few blocks. #183.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784771
