### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#284]
Tracking issue for tests we need to run.

- [ ] Create a comprehensive release test setup #192.
- [ ] Test syncing different forks #283.
- [ ] Integration tests should clean the state between one run and another #190.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784767
