### ISSUE TITLE
Blocks

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#299]
Tracking ticket for block-related things.

- [x] Canonical header hashing #297.
- [ ] Broadcast block after adding it to the top of our chain #295.
- [ ] Adjust the timestamp of the genesis block #294.
- [ ] Mine the genesis block #293.
- [ ] Fill in missing blocks #292.
- [ ] Process received block #281.
- [ ] Validate received block #17.
- [ ] Make sure the block reward cannot be claimed for the next few blocks. #183.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784791
