### ISSUE TITLE
Node

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#300]
Tracking ticket for things that deal with node startup, etc.

- [ ] Create key pair and account when node starts #204.
- [ ] Validate decrypted keys #189.
- [ ] Decide what metrics to track #286.
- [ ] Let users generate a unique address whenever they want to receive tokens #21.
- [ ] Rename packages to `epoch-<version>-<platform>.tar.gz` #213.
- [ ] Dynamic release package version #212.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/epic/show/3784762
